name: flutter_article_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  http: ^1.2.1
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.3.0
  mocktail: ^1.0.1
  build_runner: ^2.1.0
  bloc_test: ^9.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
